platform :ios, '6.0' 
pod 'SHAlertViewBlocks', :path => '../'
pod 'SHSegueBlocks'
pod 'SHBarButtonItemBlocks'

target :ExampleTests do
  pod 'SHTestCaseAdditions', :git => "https://github.com/seivan/SHTestCaseAdditions"
  pod 'SHFastEnumerationProtocols', :git => "https://github.com/PodFactory/SHFastEnumerationProtocols"
  pod "KIF-next"
end
